title: Kevin A. McCabe # your name (or website title) here
logo: "/images/km.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a professor of Economics at George Mason University.    
  <br><br>
  <a href="https://scholar.google.com/citations?user=DB4YOI4AAAAJ&hl=en&oi=ao">Google Scholar Page</a>  
  <br><br>
  <a href="https://economics.gmu.edu/people/kmccabe">My Department Website</a> 
  <br><br>
  <a href="https://kmccabe.github.io/sample_page">Publications by Topic</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
